package FamilyExpenses.Presenters.Gui;

import FamilyExpenses.Application.Dto.User.LoginResponseDto;
import FamilyExpenses.Presenters.Gui.Family.VentanaCrudFamilia;
import FamilyExpenses.Presenters.Gui.User.UpdateUserWindows;
import FamilyExpenses.Presenters.Gui.User.LoginWindow;

/**
 *
 * @author John Carlos Arrieta
 */
public class MainWindow extends javax.swing.JFrame {

    private LoginResponseDto loginResponse;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public MainWindow() {
        initComponents();
    }

    public void setLoginResponse(LoginResponseDto loginResponse) {
        this.loginResponse = loginResponse;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraDeMenu = new javax.swing.JMenuBar();
        userMenu = new javax.swing.JMenu();
        itemCloseUserSession = new javax.swing.JMenuItem();
        itemUserUpdate = new javax.swing.JMenuItem();
        itemCloseUserAcount = new javax.swing.JMenuItem();
        itemChangeUserPassword = new javax.swing.JMenuItem();
        menberMenu = new javax.swing.JMenu();
        familyMenu = new javax.swing.JMenu();
        itemNuevaFamilia = new javax.swing.JMenuItem();
        sourceMenu = new javax.swing.JMenu();
        incomeMenu = new javax.swing.JMenu();
        categoryMenu = new javax.swing.JMenu();
        expenseMenu = new javax.swing.JMenu();
        savingsFund = new javax.swing.JMenu();
        contibuteMenu = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema para gestión de finanzas familiares");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        userMenu.setMnemonic('U');
        userMenu.setText("Usuarios");

        itemCloseUserSession.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemCloseUserSession.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyExpenses/Presenters/Gui/Icons/logout24px.png"))); // NOI18N
        itemCloseUserSession.setMnemonic('C');
        itemCloseUserSession.setText("Cerrar sesion...");
        itemCloseUserSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCloseUserSessionActionPerformed(evt);
            }
        });
        userMenu.add(itemCloseUserSession);

        itemUserUpdate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemUserUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FamilyExpenses/Presenters/Gui/Icons/actulizar-usuario24px.png"))); // NOI18N
        itemUserUpdate.setText("Actualizar perfil...");
        itemUserUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUserUpdateActionPerformed(evt);
            }
        });
        userMenu.add(itemUserUpdate);

        itemCloseUserAcount.setText("Cerrar cuenta");
        userMenu.add(itemCloseUserAcount);

        itemChangeUserPassword.setText("Cambiar password...");
        userMenu.add(itemChangeUserPassword);

        barraDeMenu.add(userMenu);

        menberMenu.setText("Miembros");
        barraDeMenu.add(menberMenu);

        familyMenu.setText("Familias");

        itemNuevaFamilia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemNuevaFamilia.setText("Nueva...");
        itemNuevaFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNuevaFamiliaActionPerformed(evt);
            }
        });
        familyMenu.add(itemNuevaFamilia);

        barraDeMenu.add(familyMenu);

        sourceMenu.setText("Fuentes");
        barraDeMenu.add(sourceMenu);

        incomeMenu.setText("Ingresos");
        barraDeMenu.add(incomeMenu);

        categoryMenu.setText("Categorias");
        barraDeMenu.add(categoryMenu);

        expenseMenu.setText("Gastos");
        barraDeMenu.add(expenseMenu);

        savingsFund.setText("Bolsas de Ahorros");
        barraDeMenu.add(savingsFund);

        contibuteMenu.setText("Aportes");
        barraDeMenu.add(contibuteMenu);

        helpMenu.setText("Ayuda");
        barraDeMenu.add(helpMenu);

        setJMenuBar(barraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    public LoginResponseDto getLoginResponse() {
        return loginResponse;
    }

    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LoginWindow window = new LoginWindow(this, true, this);
        window.setLocationRelativeTo(this);
        window.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void itemCloseUserSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCloseUserSessionActionPerformed
        LoginWindow ventana = new LoginWindow(this, true, this);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemCloseUserSessionActionPerformed

    private void itemUserUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUserUpdateActionPerformed
       UpdateUserWindows window = new UpdateUserWindows(this, true);
       window.setLocationRelativeTo(this);
       window.setMainWindow(this);
       window.setVisible(true);
       
    }//GEN-LAST:event_itemUserUpdateActionPerformed

    private void itemNuevaFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNuevaFamiliaActionPerformed
       var window = new VentanaCrudFamilia(this, true);
       window.setMainWindows(this);
       window.setLocationRelativeTo(this);
       window.setTitle("Gestion de famlias");
       window.setVisible(true);
    }//GEN-LAST:event_itemNuevaFamiliaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JMenu categoryMenu;
    private javax.swing.JMenu contibuteMenu;
    private javax.swing.JMenu expenseMenu;
    private javax.swing.JMenu familyMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu incomeMenu;
    private javax.swing.JMenuItem itemChangeUserPassword;
    private javax.swing.JMenuItem itemCloseUserAcount;
    private javax.swing.JMenuItem itemCloseUserSession;
    private javax.swing.JMenuItem itemNuevaFamilia;
    private javax.swing.JMenuItem itemUserUpdate;
    private javax.swing.JMenu menberMenu;
    private javax.swing.JMenu savingsFund;
    private javax.swing.JMenu sourceMenu;
    private javax.swing.JMenu userMenu;
    // End of variables declaration//GEN-END:variables
}
