/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GastosFamiliares.Vistas.Gui;

import GastosFamiliares.Modelo.Dto.Usuarios.LoginRespuestaDto;
import GastosFamiliares.Vistas.Gui.Usuarios.VentanaActualizar;
import GastosFamiliares.Vistas.Gui.Usuarios.VentanaLogin;

/**
 *
 * @author pc
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private LoginRespuestaDto usuarioLogeado;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    public void setUsuarioLogeado(LoginRespuestaDto usuarioLogeado) {
        this.usuarioLogeado = usuarioLogeado;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraDeMenu = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        itemCerrarSesionUsuario = new javax.swing.JMenuItem();
        itemActualizarUsuario = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuMiembros = new javax.swing.JMenu();
        menuFamilias = new javax.swing.JMenu();
        menuFuentes = new javax.swing.JMenu();
        menuIngresos = new javax.swing.JMenu();
        menuCategorias = new javax.swing.JMenu();
        menuGastos = new javax.swing.JMenu();
        menuBolsasDeAhorros = new javax.swing.JMenu();
        menuAportes = new javax.swing.JMenu();
        menuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema para gestión de finanzas familiares");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        menuUsuarios.setMnemonic('U');
        menuUsuarios.setText("Usuarios");

        itemCerrarSesionUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemCerrarSesionUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GastosFamiliares/Vistas/Gui/Iconos/logout24px.png"))); // NOI18N
        itemCerrarSesionUsuario.setMnemonic('C');
        itemCerrarSesionUsuario.setText("Cerrar sesion...");
        itemCerrarSesionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarSesionUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemCerrarSesionUsuario);

        itemActualizarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemActualizarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GastosFamiliares/Vistas/Gui/Iconos/actulizar-usuario24px.png"))); // NOI18N
        itemActualizarUsuario.setText("Actualizar perfil...");
        itemActualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActualizarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemActualizarUsuario);

        jMenuItem3.setText("Cerrar cuenta");
        menuUsuarios.add(jMenuItem3);

        jMenuItem4.setText("Cambiar password...");
        menuUsuarios.add(jMenuItem4);

        barraDeMenu.add(menuUsuarios);

        menuMiembros.setText("Miembros");
        barraDeMenu.add(menuMiembros);

        menuFamilias.setText("Familias");
        barraDeMenu.add(menuFamilias);

        menuFuentes.setText("Fuentes");
        barraDeMenu.add(menuFuentes);

        menuIngresos.setText("Ingresos");
        barraDeMenu.add(menuIngresos);

        menuCategorias.setText("Categorias");
        barraDeMenu.add(menuCategorias);

        menuGastos.setText("Gastos");
        barraDeMenu.add(menuGastos);

        menuBolsasDeAhorros.setText("Bolsas de Ahorros");
        barraDeMenu.add(menuBolsasDeAhorros);

        menuAportes.setText("Aportes");
        barraDeMenu.add(menuAportes);

        menuAyuda.setText("Ayuda");
        barraDeMenu.add(menuAyuda);

        setJMenuBar(barraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    public LoginRespuestaDto getUsuarioLogeado() {
        return usuarioLogeado;
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        VentanaLogin ventana = new VentanaLogin(this, true, this);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void itemCerrarSesionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarSesionUsuarioActionPerformed
        VentanaLogin ventana = new VentanaLogin(this, true, this);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_itemCerrarSesionUsuarioActionPerformed

    private void itemActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActualizarUsuarioActionPerformed
       VentanaActualizar ventana = new VentanaActualizar(this, true);
       ventana.setLocationRelativeTo(this);
       ventana.setVentanaPrincipal(this);
       ventana.setVisible(true);
       
    }//GEN-LAST:event_itemActualizarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JMenuItem itemActualizarUsuario;
    private javax.swing.JMenuItem itemCerrarSesionUsuario;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu menuAportes;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuBolsasDeAhorros;
    private javax.swing.JMenu menuCategorias;
    private javax.swing.JMenu menuFamilias;
    private javax.swing.JMenu menuFuentes;
    private javax.swing.JMenu menuGastos;
    private javax.swing.JMenu menuIngresos;
    private javax.swing.JMenu menuMiembros;
    private javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
