/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GastosFamiliares.Vistas.Gui;

import GastosFamiliares.Modelo.Dto.Usuarios.LoginRespuestaVista;
import GastosFamiliares.Vistas.Gui.Usuarios.VentanaLogin;

/**
 *
 * @author pc
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private LoginRespuestaVista usuarioLogeado;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    public void setUsuarioLogeado(LoginRespuestaVista usuarioLogeado) {
        this.usuarioLogeado = usuarioLogeado;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraDeMenu = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuMiembros = new javax.swing.JMenu();
        menuFamilias = new javax.swing.JMenu();
        menuFuentes = new javax.swing.JMenu();
        menuIngresos = new javax.swing.JMenu();
        menuCategorias = new javax.swing.JMenu();
        menuGastos = new javax.swing.JMenu();
        menuBolsasDeAhorros = new javax.swing.JMenu();
        menuAportes = new javax.swing.JMenu();
        menuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema para gestión de finanzas familiares");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        menuUsuarios.setText("Usuarios");

        jMenuItem1.setText("Cerrar sesion...");
        menuUsuarios.add(jMenuItem1);

        jMenuItem2.setText("Actualizar perfil...");
        menuUsuarios.add(jMenuItem2);

        jMenuItem3.setText("Cerrar cuenta");
        menuUsuarios.add(jMenuItem3);

        jMenuItem4.setText("Cambiar password...");
        menuUsuarios.add(jMenuItem4);

        barraDeMenu.add(menuUsuarios);

        menuMiembros.setText("Miembros");
        barraDeMenu.add(menuMiembros);

        menuFamilias.setText("Familias");
        barraDeMenu.add(menuFamilias);

        menuFuentes.setText("Fuentes");
        barraDeMenu.add(menuFuentes);

        menuIngresos.setText("Ingresos");
        barraDeMenu.add(menuIngresos);

        menuCategorias.setText("Categorias");
        barraDeMenu.add(menuCategorias);

        menuGastos.setText("Gastos");
        barraDeMenu.add(menuGastos);

        menuBolsasDeAhorros.setText("Bolsas de Ahorros");
        barraDeMenu.add(menuBolsasDeAhorros);

        menuAportes.setText("Aportes");
        barraDeMenu.add(menuAportes);

        menuAyuda.setText("Ayuda");
        barraDeMenu.add(menuAyuda);

        setJMenuBar(barraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        VentanaLogin ventana = new VentanaLogin(this, true, this);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu menuAportes;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuBolsasDeAhorros;
    private javax.swing.JMenu menuCategorias;
    private javax.swing.JMenu menuFamilias;
    private javax.swing.JMenu menuFuentes;
    private javax.swing.JMenu menuGastos;
    private javax.swing.JMenu menuIngresos;
    private javax.swing.JMenu menuMiembros;
    private javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
